/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fpoly.qlsv.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author hoang
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDoiMatKhau = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnQLTTSV = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnQLDiem = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnQLLop = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnQLGV = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnQLLichHoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangKy = new javax.swing.JMenuItem();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQLTTSV = new javax.swing.JMenuItem();
        mniQLD = new javax.swing.JMenuItem();
        mniQLLop = new javax.swing.JMenuItem();
        mniQLGV = new javax.swing.JMenuItem();
        mniQLHocPhi = new javax.swing.JMenuItem();
        mniQLHocBong = new javax.swing.JMenuItem();
        mniQLTotNghiep = new javax.swing.JMenuItem();
        mniQLLichHoc = new javax.swing.JMenuItem();
        mniQLVayVon = new javax.swing.JMenuItem();
        mniKTKL = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniGioiThieu = new javax.swing.JMenuItem();
        mniLienHe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);

        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);
        jToolBar1.add(jSeparator2);

        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDoiMatKhau);
        jToolBar1.add(jSeparator3);

        btnQLTTSV.setText("Quản Lý TTSV");
        btnQLTTSV.setFocusable(false);
        btnQLTTSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLTTSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLTTSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTTSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLTTSV);
        jToolBar1.add(jSeparator4);

        btnQLDiem.setText("Quản Lý Điểm");
        btnQLDiem.setFocusable(false);
        btnQLDiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLDiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLDiem);
        jToolBar1.add(jSeparator5);

        btnQLLop.setText("Quản Lý Lớp");
        btnQLLop.setFocusable(false);
        btnQLLop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLLop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLopActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLLop);
        jToolBar1.add(jSeparator6);

        btnQLGV.setText("Quản Lý Giảng Viên");
        btnQLGV.setFocusable(false);
        btnQLGV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLGV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLGV);
        jToolBar1.add(jSeparator7);

        btnQLLichHoc.setText("Lịch Học");
        btnQLLichHoc.setFocusable(false);
        btnQLLichHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLLichHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLLichHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLichHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLLichHoc);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/qlsv/icon/Chao.jpg"))); // NOI18N

        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/qlsv/icon/clock (1).png"))); // NOI18N
        lblTime.setText("12:14:53 PM");

        mnuHeThong.setText("Hệ Thống");

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangNhap.setText("Đăng Nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDangKy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangKy.setText("Đăng Ký");
        mnuHeThong.add(mniDangKy);

        mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMatKhau.setText("Đổi Mật Khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator1);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setText("Đăng Xuất");
        mnuHeThong.add(mniDangXuat);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setText("Quản Lý");

        mniQLTTSV.setText("QL Sinh Viên");
        mniQLTTSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLTTSVActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLTTSV);

        mniQLD.setText("QL Điểm");
        mniQLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLDActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLD);

        mniQLLop.setText("QL Lớp");
        mniQLLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLLopActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLLop);

        mniQLGV.setText("QL Giảng Viên");
        mniQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLGVActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLGV);

        mniQLHocPhi.setText("QL Học Phí");
        mniQLHocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLHocPhiActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLHocPhi);

        mniQLHocBong.setText("QL Học Bổng");
        mniQLHocBong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLHocBongActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLHocBong);

        mniQLTotNghiep.setText("QL Tốt Nghiệp");
        mniQLTotNghiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLTotNghiepActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLTotNghiep);

        mniQLLichHoc.setText("QL Lịch Học");
        mnuQuanLy.add(mniQLLichHoc);

        mniQLVayVon.setText("Vay Vốn");
        mniQLVayVon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLVayVonActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniQLVayVon);

        mniKTKL.setText("Khen Thưởng/Kỷ Luật");
        mniKTKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKTKLActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKTKL);

        jMenuBar1.add(mnuQuanLy);

        mnuTroGiup.setText("Trợ Giúp");

        mniGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniGioiThieu.setText("Giới Thiệu Phần Mềm");
        mnuTroGiup.add(mniGioiThieu);

        mniLienHe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniLienHe.setText("Liên Hệ");
        mnuTroGiup.add(mniLienHe);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTime)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMK mk = new DoiMK();
        mk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnQLTTSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTTSVActionPerformed
        // TODO add your handling code here:
        QLTTSV sv = new QLTTSV();
        sv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLTTSVActionPerformed

    private void btnQLDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDiemActionPerformed
        // TODO add your handling code here:
        QLDSV dsv = new QLDSV();
        dsv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDiemActionPerformed

    private void btnQLLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLopActionPerformed
        // TODO add your handling code here:
        QLLH lop = new QLLH();
        lop.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLLopActionPerformed

    private void btnQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGVActionPerformed
        // TODO add your handling code here:
        homeGV gc = new homeGV();
        gc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLGVActionPerformed

    private void btnQLLichHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLichHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLLichHocActionPerformed

    private void mniQLVayVonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLVayVonActionPerformed
        // TODO add your handling code here:
        VayVon vv = new VayVon();
        vv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniQLVayVonActionPerformed

    private void mniKTKLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKTKLActionPerformed
        // TODO add your handling code here:
        KhenThuongKyLuat kt = new KhenThuongKyLuat();
        kt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniKTKLActionPerformed

    private void mniQLTotNghiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLTotNghiepActionPerformed
        // TODO add your handling code here:
        QLTN tn = new QLTN();
        tn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniQLTotNghiepActionPerformed

    private void mniQLHocBongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLHocBongActionPerformed
        // TODO add your handling code here:
        QLHB hb = new QLHB();
        hb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniQLHocBongActionPerformed

    private void mniQLHocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLHocPhiActionPerformed
        // TODO add your handling code here:
        HocPhi hp = new HocPhi();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniQLHocPhiActionPerformed

    private void mniQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLGVActionPerformed
        // TODO add your handling code here:
        homeGV gc = new homeGV();
        gc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniQLGVActionPerformed

    private void mniQLLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLLopActionPerformed
        // TODO add your handling code here:
        QLLH lop = new QLLH();
        lop.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mniQLLopActionPerformed

    private void mniQLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLDActionPerformed
        // TODO add your handling code here:
        QLDSV dsv = new QLDSV();
        dsv.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_mniQLDActionPerformed

    private void mniQLTTSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLTTSVActionPerformed
        // TODO add your handling code here:
        QLTTSV sv = new QLTTSV();
        sv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniQLTTSVActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMK mk = new DoiMK();
        mk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnQLDiem;
    private javax.swing.JButton btnQLGV;
    private javax.swing.JButton btnQLLichHoc;
    private javax.swing.JButton btnQLLop;
    private javax.swing.JButton btnQLTTSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mniDangKy;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniKTKL;
    private javax.swing.JMenuItem mniLienHe;
    private javax.swing.JMenuItem mniQLD;
    private javax.swing.JMenuItem mniQLGV;
    private javax.swing.JMenuItem mniQLHocBong;
    private javax.swing.JMenuItem mniQLHocPhi;
    private javax.swing.JMenuItem mniQLLichHoc;
    private javax.swing.JMenuItem mniQLLop;
    private javax.swing.JMenuItem mniQLTTSV;
    private javax.swing.JMenuItem mniQLTotNghiep;
    private javax.swing.JMenuItem mniQLVayVon;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuTroGiup;
    // End of variables declaration//GEN-END:variables

    private void startClock() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat fomarter = new SimpleDateFormat("hh:mm:ss a");
                String text = fomarter.format(now);
                lblTime.setText(text);
            }
        }).start();
    }

}
